services:
  postgres:
    container_name: postgres_container
    image: postgres:14
    environment:
      POSTGRES_USER: samnang
      POSTGRES_PASSWORD: samnang
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./init-multi-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5532:5432"
    networks:
      - backend
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5055:80"
    networks:
      - backend
    restart: unless-stopped

  mongo:
    container_name: mongo_container
    image: mongo:latest
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - backend
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
  mongo-express:
    container_name: mongo_express
    image: mongo-express:latest
    networks:
      - backend
    environment:
      ME_CONFIG_MONGODB_ADMINURL: "mongodb://mongo:27017/"
      #ME_CONFIG_MONGODB_ADMINURL: "mongodb://admin:admin@mongo:27017/"
    ports:
      - "8088:8081"  # Expose port 8081 for the web UI

  rabbitmq:
    container_name: rabbitmq_container
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
      - '5672:5672' # Broker Port
      - '15672:15672' # GUI Management
    networks:
      - backend
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:

