spring:
  cloud:
    gateway:
      routes:
#        - id: product-service
#          uri: lb://PRODUCT
#          predicates:
#            - Path=/api/products/**
#        - id: user-service
#          uri: lb://USER
#          predicates:
#            - Path=/api/users/**
#        - id: order-service
#          uri: lb://ORDER
#          predicates:
#            - Path=/api/orders/**
#            - Path=/api/cart/**
#        - id: eureka-server
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka
#          filters:
#            - SetPath=/
#        - id: eureka-server-static
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/**

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enable: true

# Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      ecomBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based


#logging:
#  level:
#    root: info
#    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO,
#    org.springframework.cloud.gateway: TRACE



