
spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://localhost:5532/product
    # url: jdbc:postgresql://ep-mute-paper-a13kuyam-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_fpH43qMjrORd&sslmode=require&channelBinding=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:productdb
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create


server:
  port: 8081

management:
  endpoint:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


